### ISSUE TITLE
Research: Puppeteer with Hapi

### ISSUE THREAD

**Issue by ap2322** [Tweet-311-Denver/tweet_311_denver_service#2]
Research the use of Puppeteer package to fill out forms on external websites - specifically the Denver 311 form: https://www.denvergov.org/pocketgov/#/report-a-problem

**Comment by Dustin-Mikusko** [comment]
Puppeteer can be used to fill out the form and select the options I've found. But I've also seen that the 311 form is submitted through and API. maybe it'd be easier if we submitted straight to that API also? `https://www.denvergov.org/api/AskDenver/`
